// Get day of year and convert to number
var now = new Date();
var start = new Date(now.getFullYear(), 0, 0);
var diff = now - start;
var oneDay = 1000 * 60 * 60 * 24;
var day = Math.floor(diff / oneDay);
console.log("Today is day number " + day + " out of 365 yeardays.");

// Quote list
var quotes = [
["If you have more than three priorities, then you don't have any.", "Jim Collins"],
["If babies held the same tendency toward self-criticism as adults, they might never learn to walk or talk.", "Dan Millman"],
["Be patient. Nothing worth doing is worth doing quickly. Nothing worth building is worth building in a rush. Nothing of value is formed in a minute.", "Nic Haralambous"],
["The successful warrior is the average man, with laser-like focus.", "Bruce Lee"],
["Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.", "Marcus Aurelius"],
["If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", "Jim Rohn"],
["Luxury is not a necessity to me, but beautiful and good things are.", "Anaïs Nin"],
["Be the change that you wish to see in the world.", "Mahatma Gandhi"],
["It is the way one treats his inferiors more than the way he treats his equals which reveals one’s real character.", "Charles Bayard Miliken"],
["We have to continually be jumping off cliffs and developing our wings on the way down.", "Kurt Vonnegut"],
["There are two ways to get enough. One is to continue to accumulate more and more. The other is to desire less.", "G.K. Chesterton"],
["The very least you can do in your life is figure out what you hope for. And the most you can do is live inside that hope. Not admire it from a distance but live right in it, under its roof.", "Barbara Kingsolver"],
["Creativity takes courage.", "Henri Matisse"],
["The lyf so short, the craft so long to lerne.", "Geoffrey Chaucer"],
["And now that you don't have to be perfect, you can be good.", "John Steinbeck"],
["And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye.", "Antoine de Saint-Exupéry"],
["Let every dawn be to you as the beginning of life, and every setting sun be to you as its close.", "John Ruskin"],
["Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"],
["Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure, than to take rank with those poor spirits who neither enjoy much nor suffer much, because they live in the gray twilight that knows neither victory nor defeat.", "Theodore Roosevelt"],
["To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "Ralph Waldo Emerson"],
["Act as if what you do makes a difference. It does.", "William James"],
["Little by little, one travels far.", "J.R.R. Tolkien"],
["Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", "Lao Tzu"],
["You never know what worse luck your bad luck has saved you from.", "Cormac McCarthy"],
["Having a low opinion of yourself is not 'modesty.' It's self-destruction. Holding your uniqueness in high regard is not 'egotism.' It's a necessary precondition to happiness and success.", "Bobbe Sommer"],
["For every minute you are angry you lose sixty seconds of happiness.", "Ralph Waldo Emerson"],
["I love deadlines. I love the whooshing noise they make as they go by.", "Douglas Adams"],
["Treat every moment as your last. It is not preparation for something else.", "Shunryu Suzuki"],
["Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", "Thomas Edison"],
["The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"],
["What would life be if we had no courage to attempt anything?", "Vincent van Gogh"],
["The only way to do great work is to love what you do.", "Steve Jobs"],
["If you can't explain it to a six year old, you don't understand it yourself.", "Albert Einstein"],
["Folks are usually about as happy as they make their minds up to be.", "Abraham Lincoln"],
["Life is a straight drink—hot pleasure, hot pain, straightforward, one hundred percent.", "Chögyam Trungpa"],
["It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.", "J.K. Rowling"],
["Every strike brings me closer to the next home run.", "Babe Ruth"],
["A loving heart is the truest wisdom.", "Charles Dickens"],
["Whether you think you can or you think you can’t, you’re right.", "Henry Ford"],
["If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", "Lao Tzu"],
["Dreaming, after all, is a form of planning.", "Gloria Steinem"],
["As I have said, the first thing is to be honest with yourself. You can never have an impact on society if you have not changed yourself... Great peacemakers are all people of integrity, of honesty, but humility.", "Nelson Mandela"],
["It takes a long time to become young.", "Pablo Picasso"],
["Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", "Albert Schweitzer"],
["Curiosity is one of the permanent and certain characteristics of a vigorous intellect.", "Samuel Johnson"],
["To banish imperfection is to destroy expression, to check exertion, to paralyze vitality.", "John Ruskin"],
["Do every act of your life as though it were the very last act of your life.", "Marcus Aurelius"],
["The mind is everything. What you think you become.", "Gautama Buddha"],
["Eighty percent of success is showing up.", "Woody Allen"],
["The worst enemy to creativity is self-doubt.", "Sylvia Plath"],
["Always be yourself, express yourself, have faith in yourself, do not go out and look for a successfull personality and duplicate it.", "Bruce Lee"],
["Strive not to be a success, but rather to be of value.", "Albert Einstein"],
["The most difficult thing is the decision to act, the rest is merely tenacity.", "Amelia Earhart"],
["I can’t afford to hate anyone. I don’t have that kind of time.", "Akira Kurosawa"],
["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
["Two roads diverged in a wood, and I—I took the one less traveled by, and that has made all the difference.", "Robert Frost"],
["Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.", "Ralph Waldo Emerson"],
["It always seems impossible until it's done.", "Nelson Mandela"],
["Courage starts with showing up and letting ourselves be seen.", "Brené Brown"],
["The question isn't who is going to let me; it's who is going to stop me.", "Ayn Rand"],
["You must be the change you wish to see in the world.", "Mahatma Gandhi"],
["Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.", "Helen Keller"],
["Only put off until tomorrow what you are willing to die having left undone.", "Pablo Picasso"],
["Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.", "Martin Luther"],
["Never let the fear of striking out get in your way.", "Babe Ruth"],
["We have more possibilities available in each moment than we realize.", "Thích Nhất Hạnh"],
["Dare to live the life you have dreamed for yourself. Go forward and make your dreams come true.", "Ralph Waldo Emerson"],
["I have never let my schooling interfere with my education.", "Mark Twain"],
["All progress takes place outside the comfort zone.", "Michael John Bobak"],
["I’ve seen how you can’t learn anything when you’re trying to look like the smartest person in the room.", "Barbara Kingsolver"],
["I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"],
["If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.", "Henry David Thoreau"],
["A wise man will make more opportunities than he finds.", "Francis Bacon"],
["It takes courage to grow up and become who you really are.", "E.E. Cummings"],
["Do not wait; the time will never be ‘just right.’ Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.", "Napoleon Hill"],
["The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", "Mark Twain"],
["I have looked in the mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?' And whenever the answer has been 'No' for too many days in a row, I know I need to change something.", "Steve Jobs"],
["The most common way people give up their power is by thinking they don’t have any.", "Alice Walker"],
["Success is stumbling from failure to failure with no loss of enthusiasm.", "Winston Churchill"],
["It is easy in the world to live after the world's opinion; it is easy in solitude to live after our own; but the great man is he who in the midst of the crowd keeps with perfect sweetness the independence of solitude.", "Ralph Waldo Emerson"],
["In the beginner’s mind there are many possibilities, but in the expert’s there are few.", "Shunryu Suzuki"],
["The highest reward for a man's toil is not what he gets for it but what he becomes by it.", "John Ruskin"],
["Success is the progressive realization of a worthy goal or ideal.", "Earl Nightingale"],
["I am the captain of my soul.", "Nelson Mandela"],
["I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.", "Jimi Hendrix"],
["Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen.", "John Steinbeck"],
["Life is 10% what happens to me and 90% of how I react to it.", "Charles Swindoll"],
["Continuous effort - not strength or intelligence - is the key to unlocking our potential.", "Winston Churchill"],
["The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", "Marcus Aurelius"],
["Knowing yourself is the beginning of all wisdom.", "Aristotle"],
["You must expect great things of yourself before you can do them.", "Michael Jordan"],
["Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"],
["Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.", "Mark Twain"],
["All great achievements require time.", "Maya Angelou"],
["The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"],
["We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.", "Gautama Buddha"],
["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"],
["Diligence is the mother of good luck.", "Benjamin Franklin"],
["Chase the vision, not the money; the money will end up following you.", "Tony Hsieh"],
["If you care about what you do and work hard at it, there isn't anything you can't do if you want to.", "Jim Henson"],
["Imperfection is in some sort essential to all that we know in life.", "John Ruskin"],
["Action is the foundational key to all success.", "Pablo Picasso"],
["Few things are impossible to diligence and skill. Great works are performed not by strength, but by perseverance.", "Samuel Johnson"],
["Discipline is the bridge between goals and accomplishment.", "Jim Rohn"],
["Do what you feel in your heart to be right – for you’ll be criticized anyway.", "Eleanor Roosevelt"],
["The essence of warriorship, or the essence of human bravery, is refusing to give up on anyone or anything.", "Chögyam Trungpa"],
["If you want to be happy, be.", "Leo Tolstoy"],
["Peace begins with a smile.", "Mother Teresa"],
["It is hard to fail, but it is worse never to have tried to succeed.", "Theodore Roosevelt"],
["The man who moves a mountain begins by carrying away small stones.", "Confucius"],
["The place to improve the world is first in one's own heart and head and hands, and then work outward from there.", "Robert M. Pirsig"],
["You never fail until you stop trying.", "Albert Einstein"],
["If you want to be happy, set a goal that commands your thoughts, liberates your energy and inspires your hopes.", "Andrew Carnegie"],
["Care about what other people think and you will always be their prisoner.", "Lao Tzu"],
["Design can be art. Design can be aesthetics. Design is so simple, that's why it is so complicated.", "Paul Rand"],
["The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"],
["I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.", "Dr. Seuss"],
["Happiness is not something ready made. It comes from your own actions.", "Dalai Lama XIV"],
["Great things are not done by impulse, but by a series of small things brought together.", "Vincent van Gogh"],
["If you’re bored with life — you don’t get up every morning with a burning desire to do things — you don’t have enough goals.", "Lou Holtz"],
["Happiness doesn’t come from big pieces of great success, but from small advantages hammered out day by day.", "Jim Rohn"],
["Wonder is the beginning of wisdom.", "Socrates"],
["A goal is not always meant to be reached, it often serves simply as something to aim at.", "Bruce Lee"],
["I can accept failure, everyone fails at something. But I can’t accept not trying.", "Michael Jordan"],
["You can’t wait for inspiration. You have to go after it with a club.", "Jack London"],
["The best way of preparing for the future is to take good care of the present, because we know that if the present is made up of the past, then the future will be made up of the present.", "Thích Nhất Hạnh"],
["A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", "Winston Churchill"],
["To consider our petty status worries from the perspective of a thousand years hence is to be granted a rare, tranquillising glimpse of our own insignificance.", "Alain De Botton"],
["If you are going through hell, keep going.", "Winston Churchill"],
["Build your own dreams, or someone else will hire you to build theirs.", "Farrah Gray"],
["Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.", "Maya Angelou"],
["The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can’t achieve it.", "Jordan Belfort"],
["Possessions, outward success, publicity, luxury - to me these have always been contemptible. I believe that a simple and unassuming manner of life is best for everyone, best for both the body and the mind.", "Albert Einstein"],
["Resisting pain only increases its intensity.", "Chögyam Trungpa"],
["Genius is 1% talent and 99% percent hard work…", "Albert Einstein"],
["Simplicity is about subtracting the obvious and adding the meaningful.", "John Maeda"],
["It is not enough to be industrious; so are the ants. What are you industrious about?", "Henry David Thoreau"],
["Too many of us are not living our dreams because we are living our fears.", "Les Brown"],
["If you think you are too small to make a difference, try sleeping with a mosquito.", "Dalai Lama XIV"],
["People rarely succeed unless they have fun in what they are doing.", "Dale Carnegie"],
["What we hope ever to do with ease, we must first learn to do with diligence.", "Samuel Johnson"],
["Man is a genius when he is dreaming.", "Akira Kurosawa"],
["It’s important to have a feedback loop, where you’re constantly thinking about what you’ve done and how you could be doing it better.", "Elon Musk"],
["Some people want it to happen, some wish it to happen, others make it happen.", "Michael Jordan"],
["I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.", "Herbert Bayard Swope"],
["There is no substitute for hard work.", "Thomas Edison"],
["I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.", "Nelson Mandela"],
["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
["A goal without a plan is just a wish.", "Antoine de Saint-Exupéry"],
["To be able to ask a question clearly is two-thirds of the way to getting it answered.", "John Ruskin"],
["Don't tell people how to do things, tell them what to do and let them surprise you with their results.", "George S. Patton, Jr."],
["Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously. And because all things have contributed to your advancement, you should include all things in your gratitude.", "Ralph Waldo Emerson"],
["Vulnerability is the birthplace of innovation, creativity and change.", "Brené Brown"],
["The trouble is if you don’t spend your life yourself, other people spend it for you.", "Peter Shaffer"],
["Facing it, always facing it, that's the way to get through. Face it.", "Joseph Conrad"],
["The gem cannot be polished without friction, nor man perfected without trials.", "Confucius"],
["There’s a better way to do it — find it.", "Thomas Edison"],
["Take the time to deliberate, but when the time for action has arrived, stop thinking and go in.", "Napoleon Bonaparte"],
["Obstacles can’t stop you. Problems can’t stop you. Most of all, other people can’t stop you. Only you can stop you.", "Jeffrey Gitomer"],
["We do not have to be ashamed of what we are. As sentient beings we have wonderful backgrounds. These backgrounds may not be particularly enlightened or peaceful or intelligent. Nevertheless, we have soil good enough to cultivate; we can plant anything in it.", "Chögyam Trungpa"],
["Everyone has talent. What's rare is the courage to follow it to the dark places where it leads.", "Erica Jong"],
["Don’t be arrogant, because arrogance kills curiosity and passion.", "Mina Bissell"],
["I have no special talent. I am only passionately curious.", "Albert Einstein"],
["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
["I have learned over the years that when one’s mind is made up, this diminishes fear.", "Rosa Parks"],
["Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", "Marcus Aurelius"],
["Trust yourself. You know more than you think you do.", "Benjamin Spock"],
["Don't try to be original; just try to be good.", "Paul Rand"],
["It's the job that's never started as takes longest to finish.", "J.R.R. Tolkien"],
["The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.", "Elie Wiesel"],
["Education is the kindling of a flame, not the filling of a vessel.", "Socrates"],
["A busy life is a wasted life.", "Francis Crick"],
["An investment in knowledge always pays the best interest.", "Benjamin Franklin"],
["Always do what you are afraid to do.", "Ralph Waldo Emerson"],
["You cannot swim for new horizons until you have courage to lose sight of the shore.", "William Faulkner"],
["To hell with circumstances; I create opportunities.", "Bruce Lee"],
["When I let go of what I am, I become what I might be.", "Lao Tzu"],
["A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.", "Douglas Adams"],
["You’ve got to jump off cliffs and build your wings on the way down.", "Ray Bradbury"],
["Everything must be made as simple as possible. But not simpler.", "Albert Einstein"],
["Every child is an artist. The problem is how to remain an artist once he grows up.", "Pablo Picasso"],
["No matter how great the talent or efforts, some things just take time. You can't produce a baby in one month by getting nine women pregnant.", "Warren Buffett"],
["The perfect is the enemy of the good.", "Voltaire"],
["Clutter and confusion are failures of design, not attributes of information.", "Edward R. Tufte"],
["The really important thing is not to live, but to live well. And to live well meant, along with more enjoyable things in life, to live according to your principles.", "Socrates"],
["The scariest moment is always just before you start.", "Stephen King"],
["Think of yourself as dead. You have lived your life. Now, take what's left and live it properly.", "Marcus Aurelius"],
["A man is but the product of his thoughts; what he thinks, he becomes.", "Mahatma Gandhi"],
["Our lives begin to end the day we become silent about things that matter.", "Martin Luther King, Jr."],
["Peace of mind produces right values, right values produce right thoughts. Right thoughts produce right actions and right actions produce work which will be a material reflection for others to see of the serenity at the center of it all.", "Robert M. Pirsig"],
["Simplify, simplify, simplify.", "Henry David Thoreau"],
["One's dignity may be assaulted, vandalized and cruelly mocked, but it can never be taken away unless it is surrendered.", "Michael J. Fox"],
["Learn the rules like a pro, so you can break them like an artist.", "Pablo Picasso"],
["Keeping your body healthy is an expression of gratitude to the whole cosmos - the trees, the clouds, everything.", "Thích Nhất Hạnh"],
["Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty… I have never in my life envied a human being who led an easy life. I have envied a great many people who led difficult lives and led them well.", "Theodore Roosevelt"],
["You can’t use up creativity. The more you use, the more you have.", "Maya Angelou"],
["The good news is that the moment you decide that what you know is more important than what you have been taught to believe, you will have shifted gears in your quest for abundance. Success comes from within, not from without.", "Ralph Waldo Emerson"],
["There are only two mistakes one can make along the road to truth; not going all the way, and not starting.", "Gautama Buddha"],
["Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart.", "Steve Jobs"],
["You miss 100% of the shots you don’t take.", "Wayne Gretzky"],
["The only Zen you find on tops of mountains is the Zen you bring there.", "Robert M. Pirsig"],
["Sometimes I lie awake at night and I ask, 'Is life a multiple choice test or is it a true or false test?' ...Then a voice comes to me out of the dark and says, 'We hate to tell you this but life is a thousand word essay.'", "Charles M. Schulz"],
["You don’t learn to walk by following rules. You learn by doing, and by falling over.", "Richard Branson"],
["I am always doing that which I can not do, in order that I may learn how to do it.", "Pablo Picasso"],
["Our greatest glory is not in never failing, but in rising up every time we fail.", "Ralph Waldo Emerson"],
["If you look at what you have in your life, you’ll always have more. If you look at what you don’t have in your life, you’ll never have enough.", "Oprah Winfrey"],
["What we play is life.", "Louis Armstrong"],
["If you're not prepared to be wrong, you'll never come up with anything original.", "Ken Robinson"],
["Stuff your eyes with wonder, live as if you’d drop dead in ten seconds. See the world.", "Ray Bradbury"],
["It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.", "Leon C. Megginson"],
["Attitude is a little thing that makes a big difference.", "Winston Churchill"],
["Absorb what is useful, reject what is useless, add what is specifically your own.", "Bruce Lee"],
["If you don’t like what you’re doing, then don’t do it.", "Ray Bradbury"],
["Try not to become a man of success. Rather become a man of value.", "Albert Einstein"],
["Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"],
["When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love …", "Marcus Aurelius"],
["Work is easier when it’s just work; it’s much harder when you actually care.", "John Maeda"],
["A winner is a dreamer who never gives up.", "Nelson Mandela"],
["I don't count my sit-ups; I only start counting when it starts hurting because they’re the only ones that count.", "Muhammad Ali"],
["Don’t judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson"],
["During your life, never stop dreaming. No one can take away your dreams.", "Tupac Shakur"],
["Guard well your spare moments. They are like uncut diamonds. Discard them and their value will never be known. Improve them and they will become the brightest gems in a useful life.", "Ralph Waldo Emerson"],
["It's not the daily increase but daily decrease. Hack away at the unessential.", "Bruce Lee"],
["He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever.", "Chinese Proverb"],
["Find joy in everything you choose to do. Every job, relationship, home... it's your responsibility to love it, or change it.", "Chuck Palahniuk"],
["Sometimes you will never know the value of a moment until it becomes a memory.", "Dr. Seuss"],
["A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd"],
["You can only come to the morning through the shadows.", "J.R.R. Tolkien"],
["Without ambition one starts nothing. Without work one finishes nothing. The prize will not be sent to you. You have to win it.", "Ralph Waldo Emerson"],
["Whatever your life’s work is, do it well.", "Martin Luther King, Jr."],
["We cannot live better than in seeking to become better.", "Socrates"],
["Don't ask yourself what the world needs. Ask yourself what makes you come alive and then go do that. Because what the world needs is people who have come alive.", "Howard Thurman"],
["It’s very easy to be different, but very difficult to be better.", "Jonathan Ive"],
["Dripping water hollows out stone, not through force but through persistence.", "Ovid"],
["We have to dare to be ourselves, however frightening or strange that self may prove to be.", "May Sarton"],
["Resentment is like drinking poison and then hoping it will kill your enemies.", "Nelson Mandela"],
["If you want to build a ship, don’t drum up the men to gather wood, divide the work and give orders. Instead, teach them to yearn for the vast and endless sea.", "Antoine de Saint"],
["Happiness is not something ready made. It comes from your own actions.", "Dalai Lama XIV"],
["There is no wealth but life.", "John Ruskin"],
["The best way out is always through.", "Robert Frost"],
["I am driven by two main philosophies, know more today about the world than I knew yesterday. And lessen the suffering of others. You'd be surprised how far that gets you.", "Neil DeGrasse Tyson"],
["You can only become truly accomplished at something you love. Don't make money your goal. Instead, pursue the things you love doing, and then do them so well that people can't take their eyes off you.", "Maya Angelou"],
["In life, there are no shortcuts to joy. Anything that is worth pursuing requires us to suffer just a little bit.", "Chris Burkard"],
["Knowing is not enough; we must apply. Willing is not enough; we must do.", "Johann Wolfgang von Goethe"],
["In the name of God, stop a moment, cease your work, look around you.", "Leo Tolstoy"],
["Authenticity is a collection of choices that we have to make every day. It's about the choice to show up and be real. The choice to be honest. The choice to let our true selves be seen.", "Brené Brown"],
["Words may show a man’s wit, but actions his meaning.", "Benjamin Franklin"],
["For most of us the problem isn’t that we aim too high and fail - it’s just the opposite - we aim too low and succeed.", "Ken Robinson"],
["When you stop doing things for fun, you may as well be dead.", "Ernest Hemingway"],
["Have no fear of perfection - you’ll never reach it.", "Salvador Dali"],
["Winners are not afraid of losing. But losers are. Failure is part of the process of success. People who avoid failure also avoid success.", "Robert T. Kiyosaki"],
["Education is the most powerful weapon which you can use to change the world.", "Nelson Mandela"],
["If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus; and you must not stay there, you must go beyond them.", "Bruce Lee"],
["Don't be too timid and squeamish about your actions. All life is an experiment. The more experiments you make the better.", "Ralph Waldo Emerson"],
["The best thing about the future is that it comes one day at a time.", "Abraham Lincoln"],
["I was born not knowing and have had only a little time to change that here and there.", "Richard Feynman"],
["The best thing in life aren't things.", "John Ruskin"],
["What we know matters but who we are matters more.", "Brené Brown"],
["The first and most important thing an individual can do is to become an individual again, decontrol himself, train himself as to what is going on and win back as much independent ground for himself as possible.", "William S. Burroughs"],
["Doing the best at this moment puts you in the best place for the next moment.", "Oprah Winfrey"],
["To be beautiful means to be yourself. You don’t need to be accepted by others. You need to accept yourself.", "Thích Nhất Hạnh"],
["It's not always that we need to do more but rather that we need to focus on less.", "Nathan W. Morris"],
["Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'", "Lao Tzu"],
["Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.", "Scott Adams"],
["The superior man thinks always of virtue; the common man thinks of comfort.", "Confucius"],
["Simplicity boils down to two steps: Identify the essential. Eliminate the rest.", "Leo Babauta"],
["To be disciplined is to follow in a good way. To be self disciplined is to follow in a better way.", "Corita Kent"],
["I started my life with a single absolute: that the world was mine to shape in the image of my highest values and never to be given up to a lesser standard, no matter how long or hard the struggle.", "Ayn Rand"],
["Nature is painting for us, day after day, pictures of infinite beauty if only we have the eyes to see them.", "John Ruskin"],
["There is no way to happiness - happiness is the way.", "Thích Nhất Hạnh"],
["Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupéry"],
["Focus is a matter of deciding what things you’re not going to do.", "John Carmack"],
["There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "Aristotle"],
["Bad artists copy. Good artists steal.", "Pablo Picasso"],
["Everyone you will ever meet knows something you don't.", "Bill Nye"],
["It is not that I'm so smart. But I stay with the questions much longer.", "Albert Einstein"],
["Believe you can and you’re halfway there.", "Theodore Roosevelt"],
["Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.", "Isaac Asimov"],
["We are what we repeatedly do. Excellence, therefore, is not an act but a habit.", "Aristotle"],
["Start where you are. Use what you have. Do what you can.", "Arthur Ashe"],
["Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"],
["When love and skill work together, expect a masterpiece.", "John Ruskin"],
["Life is really simple, but we insist on making it complicated.", "Confucius"],
["Efficiency is doing things right; effectiveness is doing the right things.", "Peter Drucker"],
["The journey of a thousand miles begins with one step.", "Lao Tzu"],
["Nothing will ever be attempted if all possible objections must first be overcome.", "Samuel Johnson"],
["You have power over your mind - not outside events. Realize this, and you will find strength.", "Marcus Aurelius"],
["Curiosity is, in great and generous minds, the first passion and the last.", "Samuel Johnson"],
["The most difficult times for many of us are the ones we give ourselves.", "Pema Chödrön"],
["Dare to think for yourself.", "Voltaire"],
["It’s not just what it looks like and feels like. Design is how it works.", "Steve Jobs"],
["If you spend too much time thinking about a thing, you’ll never get it done.", "Bruce Lee"],
["Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.", "Alexander Graham Bell"],
["When it is obvious that the goals cannot be reached, don’t adjust the goals, adjust the steps.", "Confucius"],
["The truth knocks on the door and you say, 'Go away, I'm looking for the truth,' and so it goes away. Puzzling.", "Robert M. Pirsig"],
["It is never too late to be what you might have been.", "George Eliot"],
["Be happy now, without reason - or you never will be at all.", "Dan Millman"],
["If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "Vincent Van Gogh"],
["When I do good, I feel good. When I do bad, I feel bad. That's my religion.", "Abraham Lincoln"],
["Freedom lies in being bold.", "Robert Frost"],
["I’ve failed over and over and over again in my life and that is why I succeed.", "Michael Jordan"],
["This is my simple religion. There is no need for temples; no need for complicated philosophy. Our own brain, our own heart is our temple; the philosophy is kindness.", "Dalai Lama XIV"],
["If we attend continually and promptly to the little that we can do, we shall ere long be surprised to find how little remains that we cannot do.", "Samuel Butler"],
["Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like.", "Lao Tzu"],
["In the hopes of reaching the moon men fail to see the flowers that blossom at their feet.", "Albert Schweitzer"],
["Make everything as simple as possible, but not simpler.", "Albert Einstein"],
["Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", "Neil Gaiman"],
["Failure is the condiment that gives success its flavor.", "Truman Capote"],
["If you're reading this… Congratulations, you're alive. If that's not something to smile about, then I don't know what is.", "Chad Sugg"],
["Appearances matter — and remember to smile.", "Nelson Mandela"],
["Quality is never an accident; it is always the result of intelligent effort.", "John Ruskin"],
["I have not failed. I’ve just found 10,000 ways that won’t work.", "Thomas Edison"],
["The miracle is not to walk on water. The miracle is to walk on the green earth, dwelling deeply in the present moment and feeling truly alive.", "Thích Nhất Hạnh"],
["Nothing will work unless you do.", "Maya Angelou"],
["Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"],
["It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams.", "Gabriel Garcí­a Márquez"],
["When I was young I observed that nine out of ten things I did were failures, so I did ten times more work.", "George Bernard Shaw"],
["Learn to value yourself, which means: fight for your happiness.", "Ayn Rand"],
["You sort of start thinking anything’s possible if you’ve got enough nerve.", "J.K. Rowling"],
["The harder the conflict, the more glorious the triumph.", "Thomas Paine"],
["If I’d observed all the rules, I’d never have got anywhere.", "Marilyn Monroe"],
["If you want to succeed, strike out on new paths rather than travel the worn paths of accepted success.", "John D. Rockefeller"],
["You’ve got enemies? Good. That means you’ve stood up for something, sometime in your life.", "Winston Churchill"],
["Simplicity is the ultimate sophistication.", "Leonardo da Vinci"],
["A rock pile ceases to be a rock pile the moment a single man contemplates it, bearing within him the image of a cathedral.", "Antoine de Saint-Exupéry"],
["Curiosity is the engine of achievement.", "Ken Robinson"],
["The way to get started is to quit talking and begin doing.", "Walt Disney"],
["A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", "George Bernard Shaw"],
["If you love life, don’t waste time, for time is what life is made up of.", "Bruce Lee"],
["Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "Johann Wolfgang von Goethe"],
["Dreams are extremely important. You can’t do it unless you imagine it.", "George Lucas"],
["A superior man is modest in his speech, but exceeds in his actions.", "Confucius"],
["Failure is the opportunity to begin again more intelligently.", "Henry Ford"],
["Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"],
["The fishermen know that the sea is dangerous and the storm terrible, but they have never found these dangers sufficient reason for remaining ashore.", "Vincent van Gogh"],
["I now see how owning our story and loving ourselves through that process is the bravest thing that we will ever do.", "Brené Brown"],
["When you are content to be simply yourself and don't compare or compete, everybody will respect you.", "Lao Tzu"],
["Life shrinks or expands in proportion to one's courage.", "Anaïs Nin"],
["I thought Star Wars was too wacky for the general public.", "George Lucas"],
["I urge you to please notice when you are happy, and exclaim or murmur or think at some point, “If this isn’t nice, I don’t know what is.”", "Kurt Vonnegut"],
["We are all failures- at least the best of us are.", "J.M. Barrie"],
["True education is concerned not only with practical goals but also with values. Our aims assure us of our material life, our values make possible our spiritual life.", "Ludwig Mies van der Rohe"],
["To be fully alive, fully human, and completely awake is to be continually thrown out of the nest.", "Pema Chödrön"],
["Happiness is when what you think, what you say, and what you do are in harmony.", "Mahatma Gandhi"],
["Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it.", "Steve Jobs"],
["Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.", "Normal Vincent Peale"],
["There are risks and costs to action. But they are far less than the long range risks of comfortable inaction.", "John F. Kennedy"],
["Work is not always required. There is such a thing as sacred idleness.", "George MacDonald"],
["It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.", "Leonardo da Vinci"],
["A thinker sees his own actions as experiments and questions--as attempts to find out something. Success and failure are for him answers above all.", "Friedrich Nietzsche"],
["There is nothing like looking, if you want to find something. You certainly usually find something, if you look, but it is not always quite the something you were after.", "J.R.R. Tolkien"],
["There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living.", "Nelson Mandela"],
["Everything is design. Everything!", "Paul Rand"],
["Creativity requires the courage to let go of certainties.", "Erich Fromm"],
["It is not death that a man should fear, but he should fear never beginning to live.", "Marcus Aurelius"],
["Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.", "Voltaire"],
["Now and then it's good to pause in our pursuit of happiness and just be happy.", "Guillaume Apollinaire"],
["Get busy living or get busy dying.", "Stephen King"],
["Courage is being scared to death, but saddling up anyway.", "John Wayne"],
["You have to allow a certain amount of time in which you are doing nothing in order to have things occur to you, to let your mind think.", "Mortimer Adler"],
["When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.", "Audre Lorde"],
["There is more to life than increasing its speed.", "Mahatma Gandhi"],
["Tension is who you think you should be. Relaxation is who you are.", "Chinese Proverb"],
["There is precious little hope to be got out of whatever keeps us industrious, but there is a chance for us whenever we cease work and become stargazers.", "H.M. Tomlinson"],
["I hope that in this year to come, you make mistakes. Because if you are making mistakes...you're Doing Something.", "Neil Gaiman"],
["There is great virtue in resting from time to time in pure awareness of the present moment, and being able to refer to this state when afflictive emotions arise so that we do not identify with them and are not swayed by them.", "Matthieu Ricard"]
];

// Get day of week and convert to number
var weekday = new Date();
var dayNumber = weekday.getDay();
//var today = dayNumber;
var today = day;
var yesterday = today -1;
var active = 0;

//Ensure yesterday always hits
if(yesterday < 0) {
	yesterday = 0;
}

//Yesterday's Quote
function getYesterday() {
       $("h1#quote").animate({"opacity": 0}, 250, function() {
           $("h1#quote").text(quotes[yesterday][0]);
       }).animate({"opacity": 1}, 1000);
		$("h2#author").animate({"opacity": 0}, 250, function() {
           $("h2#author").text(quotes[yesterday][1]);
       }).animate({"opacity": 1}, 1000);
    active = 1;
}

//Today's Quote
function getToday() {
       $("h1#quote").animate({"opacity": 0}, 250, function() {
           $("h1#quote").text(quotes[today][0]);
       }).animate({"opacity": 1}, 1000);
		$("h2#author").animate({"opacity": 0}, 250, function() {
           $("h2#author").text(quotes[today][1]);
       }).animate({"opacity": 1}, 1000);
    active = 0;
}

//console.log(quotes[dayNumber][0]);
//console.log(quotes[dayNumber][1]);
console.log("The current date is: " + weekday);
console.log("Today is day number " + dayNumber + " out of 7 weekdays.");

// Primary jQuery Functions
$(document).ready(function() {
	
	//Establish daily quote
    $("h1#quote").text(quotes[day][0]);
    $("h2#author").text(quotes[day][1]);
    
    // Yesterday button
    $('a#yesterday').click (function() {
        if(active != 1) {
       getYesterday();
	  $("a#yesterday").addClass("button-active");
	  $("a#today").removeClass("button-active");
        }
    });
    
    // Today button
    $('a#today').click(function() {
        if(active != 0) {
       getToday();
	  $("a#today").addClass("button-active");
	  $("a#yesterday").removeClass("button-active");
        }
    });
    
    //smooth scroll
   $('a').click(function(){
	$('html, body').animate({
		scrollTop: $( $(this).attr('href') ).offset().top
    }, 750);
    return false;
	});
    
})